# values.yaml
---
template:
  metadata:
    annotations: 
      github-actions-sample: restricted-scc
  spec:
    containers:
      - name: runner
        image: image-registry.openshift-image-registry.svc:5000/arc-systems/github-runner:x86-64
        command: ["/home/runner/run.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 123